language: node_js # 构建所需的语言环境

node_js:
  - "v8.12.0"  # 对应的版本

branches:
  only:
  - master    # 构建的分支

cache:
  directories:
  - node_modules # 依赖缓存的目录

before_install:
- export TZ='Asia/Shanghai'  # 设置时区

install:
 - npm install # 安装编译工具

script:
- npm run build

before_deploy:
  - git config --global user.email "boxizeng@tencent.com"
  - git config --global user.name "boxizeng"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - echo 'tagName:' $GIT_TAG
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUB_TOKEN@github.com/boxizen/wedding --tags  

deploy:
  # - provider: pages
  # skip-cleanup: true
  # github-token: $GITHUB_TOKEN # github 上的token环境变量
  # local-dir: dist ## 根据情况自定义到静态文件输出目录
  # target-branch: gh-pages
  # verbose: true
  # on:
  #   branch: master
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/*
  skip_cleanup: true
  on:
    tags: false    
